apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
    app.kubernetes.io/component: redis
    app.kubernetes.io/instance: redis
spec:
  ports:
  - port: 6379
    targetPort: 6379
    name: redis
  - port: 5000
    targetPort: 5000
    name: sentinel
  selector:
    app: redis
