apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  serviceName: redis
  replicas: 3
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      imagePullSecrets:
      - name: regsec
      initContainers:
      - name: redis-config
        imagePullPolicy: IfNotPresent
        image: git.pyxis.com.tn:5000/redis:7.0
        env:
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: redis-secret
                key: REDIS_PASSWORD
        command: [ "sh", "-c", "/scripts/redis_init.sh" ]
        volumeMounts:
        - name: redis-config
          mountPath: /etc/redis/
        - name: config
          mountPath: /tmp/redis/
        - name: init-script
          mountPath: /scripts/
      - name: sentinel-config
        imagePullPolicy: IfNotPresent
        image: git.pyxis.com.tn:5000/redis:7.0
        env:
          - name: REDIS_NODES
            valueFrom:
              configMapKeyRef:
                name: redis-config-map
                key: REDIS_NODES
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: redis-secret
                key: REDIS_PASSWORD
        command: [ "sh", "-c", "/scripts/sentinel_init.sh" ]
        volumeMounts:
        - name: redis-config-sentinel
          mountPath: /etc/redis/
        - name: sentinel-init-script
          mountPath: /scripts/
      containers:
      - name: redis
        imagePullPolicy: IfNotPresent
        image: git.pyxis.com.tn:5000/redis:7.0
        command: ["redis-server"]
        args: ["/etc/redis/redis.conf"]
        ports:
        - containerPort: 6379
          name: redis
        volumeMounts:
        - name: data
          mountPath: /data
        - name: redis-config
          mountPath: /etc/redis/

      - name: sentinel
        imagePullPolicy: IfNotPresent
        image: git.pyxis.com.tn:5000/redis:7.0
        command: ["redis-sentinel"]
        args: ["/etc/redis/sentinel.conf"]
        ports:
        - containerPort: 5000
          name: sentinel
        volumeMounts:
        - name: redis-config-sentinel
          mountPath: /etc/redis/
        - name: sentinel-data
          mountPath: /data
      volumes:
      - name: sentinel-init-script
        configMap:
          name: redis-scripts-config-map
          defaultMode: 0777
          items:
          - key: sentinel_init.sh
            path: sentinel_init.sh
      - name: redis-config-sentinel
        emptyDir: {}
      - name: sentinel-data
        emptyDir: {}
      - name: data
        emptyDir: {}
      - name: redis-config
        emptyDir: {}
      - name: init-script
        configMap:
          name: redis-scripts-config-map
          defaultMode: 0777
          items:
          - key: redis_init.sh
            path: redis_init.sh
      - name: config
        configMap:
          name: redis-config-map
          items:
          - key: redis.conf
            path: redis.conf
---
kind: Secret
apiVersion: v1
metadata:
  name: redis-secret
type: Opaque
stringData:
  REDIS_PASSWORD: "secret"
