apiVersion: v1
kind: PersistentVolume
metadata:
  name: cdr-pfs-storage

spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Gi

  # nfs:
  #   path: /NFS/vmnfs1/home/voucher-management/
  #   server: 10.25.126.154